### ISSUE TITLE
Error when running homebridge with accessory

### ISSUE THREAD

**Issue by cfort69** [flochtililoch/homebridge-lirc-accessory#1]
[12/12/2016, 10:02:16 PM] [Fan] Initializing homebridge-lirc-accessory.LIRC Accessory accessory...
/usr/local/lib/node_modules/homebridge-lirc-accessory/index.js:46
    const service = new Service[this.config.HapService]();
                    ^
I'm getting this error when I run homebridge with this accessory using sample configuration for lira-state-api and homebridge-lirc-accessory
 
TypeError: Service[this.config.HapService] is not a constructor
    at Accessory.coreService (/usr/local/lib/node_modules/homebridge-lirc-accessory/index.js:46:21)
    at Accessory.getServices (/usr/local/lib/node_modules/homebridge-lirc-accessory/index.js:94:12)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:266:26)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by flochtililoch** [comment]
sounds like an issue with your configuration file, particularly the key "hapService". What did you set in there? The name of the service should match one of the services defined [here](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2073-L2908)

**Comment by cfort69** [comment]
That does not seem to be it, I used sample config on lirc-state-api and on hombridge-lirc-accessory. Unless there is a problem with those sample configs

**Comment by flochtililoch** [comment]
Could you format your error using backticks? Your pasted error shows `this.config.HapService` but code has it with lowercase `h` [`this.config.hapService`](https://github.com/flochtililoch/homebridge-lirc-accessory/blob/master/index.js#L46).
Could you also paste your entire homebridge config?

**Comment by cfort69** [comment]
you were right it was the lower case h. Up an running now. Thanks!

**Comment by flochtililoch** [comment]
Great!
