### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by okhick** [flochtililoch/homebridge-lirc-accessory#3]
Homebridge launches and loads the accessory. It then crashes and throws the following error:

`Initializing homebridge-lirc-accessory.LIRC Accessory accessory...
/home/pi/.nvm/versions/node/v8.0.0/lib/node_modules/homebridge-lirc-accessory/index.js:75
        .on('get', getter)
        ^`

`TypeError: Cannot read property 'on' of undefined
    at wrap (/home/pi/.nvm/versions/node/v8.0.0/lib/node_modules/homebridge-lirc-accessory/index.js:75:9)
    at config.properties.forEach.property (/home/pi/.nvm/versions/node/v8.0.0/lib/node_modules/homebridge-lirc-accessory/index.js:81:7)
    at Array.forEach (native)
    at Accessory.coreService (/home/pi/.nvm/versions/node/v8.0.0/lib/node_modules/homebridge-lirc-accessory/index.js:79:28)
    at Accessory.getServices (/home/pi/.nvm/versions/node/v8.0.0/lib/node_modules/homebridge-lirc-accessory/index.js:94:12)
    at Server._createAccessory (/home/pi/.nvm/versions/node/v8.0.0/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server._loadAccessories (/home/pi/.nvm/versions/node/v8.0.0/lib/node_modules/homebridge/lib/server.js:266:26)
    at Server.run (/home/pi/.nvm/versions/node/v8.0.0/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/home/pi/.nvm/versions/node/v8.0.0/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/home/pi/.nvm/versions/node/v8.0.0/lib/node_modules/homebridge/bin/homebridge:17:22)`

I have also verified that lirc-state-api is working. Any thoughts on what is happening here?

**Comment by okhick** [comment]
Solved it! The "baseUrl" was incorrect!
