### ISSUE TITLE
Error on initialisation

### ISSUE THREAD

**Issue by jrhun** [flochtililoch/homebridge-lirc-accessory#4]
Homebridge launches and loads the accessory, but then crashes with the following error.

`
[7/11/2017, 9:20:27 AM] [Heater] Initializing homebridge-lirc-accessory.LIRC Accessory accessory...
/usr/lib/node_modules/homebridge-lirc-accessory/index.js:46
const service = new Service[this.config.hapService]();
^
TypeError: Service[this.config.hapService] is not a constructor
at Accessory.coreService (/usr/lib/node_modules/homebridge-lirc-accessory/index.js:46:21)
at Accessory.getServices (/usr/lib/node_modules/homebridge-lirc-accessory/index.js:94:12)
at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:378:36)
at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:266:26)
at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:81:38)
at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
`

I've tried a number of different options for hapService, as per this [file](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js) of homebridge Services, but still get the error.  

lirc-state-api has been tested separately and is working correctly.

**Comment by jrhun** [comment]
Upon looking into it further, I had didn't have the correct characteristics for the service type I was trying (slightly different error to above), but the file I linked to lists them all!
